/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
0 * @author DELL
 */
public class DiplomaCs extends javax.swing.JFrame {

    /**
     * Creates new form DiplomaCs
     */
    public DiplomaCs() {
        showUserGuide2();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cgpaTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("DIPLOMA CGPA:");

        jButton1.setText("Recommend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cgpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cgpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cgpaText = cgpaTF.getText();
        double cgpa = 0;
    try {
        cgpa = Double.parseDouble(cgpaText);
        if (cgpa < 2.50 || cgpa > 4.00) {
            throw new NumberFormatException("CGPA out of range");
        }
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Invalid CGPA. Please enter a value between 2.50 and 4.00.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    List<String> qualifications = List.of(
            "DIPLOMA IN COMPUTING(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA COMPUTER SCIENCE(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA SOFTWARE ENGINEERING(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA INFORMATION SYSTEM(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA KEMAHIRAN MALAYSIA(DKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA VOKASIONAL MALAYSIA(DVM) ON COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)",
            "DIPLOMA LANJUTAN KEMAHIRAN MALAYSIA(DLKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)"
        );
    
     Set<String> recommendedPrograms = new HashSet<>();
        for (String qualification : qualifications) {
            if (qualification.equals("DIPLOMA IN COMPUTING(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA COMPUTER SCIENCE(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA SOFTWARE ENGINEERING(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA INFORMATION SYSTEM(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA KEMAHIRAN MALAYSIA(DKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA LANJUTAN KEMAHIRAN MALAYSIA(DLKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)") ||
                qualification.equals("DIPLOMA VOKASIONAL MALAYSIA(DVM) ON COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)")) {
                if (cgpa >= 2.50) {
                    recommendedPrograms.add("Bachelor of Information Technology");
                    recommendedPrograms.add("Bachelor of Computer Science");
                }
            }
            
        }
        // Display recommended programs in a dialog
        StringBuilder message = new StringBuilder();
        message.append("Recommended programs:\n");
        if (recommendedPrograms.isEmpty()) {
            message.append("No suitable program found.");
        } else {
            for (String program : recommendedPrograms) {
                message.append(program).append("\n");
            }
        }
        JOptionPane.showMessageDialog(this, message.toString(), "Program Recommendation", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showUserGuide2() {
        String message = "Please enter your grade or cgpa and click the button 'recommend' to see your recommended program ";
        JOptionPane.showMessageDialog(this, message, "User Guide", JOptionPane.INFORMATION_MESSAGE);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiplomaCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiplomaCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiplomaCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiplomaCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiplomaCs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cgpaTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
