package finalproject;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Last extends javax.swing.JFrame {
    

    /**
     * Creates new form Last
     */
    public Last() {
        initComponents();
        setLocationRelativeTo(null);
        // Schedule the user guide to show after the GUI is displayed
        showUserGuide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel1.setText("PROGRAM SELECTION SYSTEM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Qualification");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(SPM/SPMV/O-LEVEL(PASS WITH 3 CREDITS INCLUDING - MATH)", "UEC(PASS WITH MINIMUM GRADE B IN 3 SUBJECT INCLUDING - MATH)", "SPM(PASS WITH 5 CREDITS)", "O-LEVEL(PASS WITH 5 CREDITS)", "UEC(PASS WITH GRADE B IN 4 SUBJECTS)", "STPM(PASS WITH MINIMUM GRADE C IN 1 SUBJECT)", "STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS AND MATH SPM)", "STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS AND ADD MATH SPM C)", "STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS + MATH SPM AND ONE OF THE SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)", "FOUNDATION IN INFORMATION TECHNOLOGY(PASS WITH MINIMUM CGPA 2.00 AND MATH(SPM) C)", "FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND MATH(SPM) C)", "FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND  ADD MATH IN SPM C)", "FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND MATH + SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)", "MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) AND MATH SPM C)", "MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) AND ADD MATH IN SPM C)", "MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) + MATH AND ONE OF THE SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)", "DIPLOMA IN COMPUTING(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA COMPUTER SCIENCE(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA SOFTWARE ENGINEERING(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA INFORMATION SYSTEM(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA KEMAHIRAN MALAYSIA(DKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA VOKASIONAL MALAYSIA(DVM) ON COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA LANJUTAN KEMAHIRAN MALAYSIA(DLKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)", "DIPLOMA IN SCIENCE AND TECHNOLOGY(PASS WITH A MINIMUM CGPA OF 2.75)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Enter you grade/cgpa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jComboBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String selectedQualification = (String) jComboBox1.getSelectedItem();
        if (selectedQualification.equals("SPM(PASS WITH 5 CREDITS)"))
        {
            Spm spmFrame;
            spmFrame = new Spm();
            spmFrame.setVisible(true);
        } else if (selectedQualification.equals("O-LEVEL(PASS WITH 5 CREDITS)")) {
            Olevel olevelFrame = new Olevel();
            olevelFrame.setVisible(true);
        } else if (selectedQualification.equals("UEC(PASS WITH GRADE B IN 4 SUBJECTS)")){
            Uec uecFrame = new Uec();
            uecFrame.setVisible(true);
        } else if (selectedQualification.equals("(SPM/SPMV/O-LEVEL(PASS WITH 3 CREDITS INCLUDING - MATH)")){
            Spmv spmvFrame = new Spmv();
            spmvFrame.setVisible(true);
        } else if (selectedQualification.equals("UEC(PASS WITH MINIMUM GRADE B IN 3 SUBJECT INCLUDING - MATH)")){
            DiplomaUec diplomauecFrame = new DiplomaUec();
            diplomauecFrame.setVisible(true);
        } else if (selectedQualification.equals( "STPM(PASS WITH MINIMUM GRADE C IN 1 SUBJECT)")){
            Stpm stpmFrame = new Stpm();
            stpmFrame.setVisible(true);
        } else if (selectedQualification.equals("STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS AND ADD MATH SPM C)")){
            AddMathStpm addmathstpmFrame = new AddMathStpm();
            addmathstpmFrame.setVisible(true);
        }else if (selectedQualification.equals("STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS + MATH SPM AND ONE OF THE SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)")){
            MathStpm mathstpmFrame = new MathStpm();
            mathstpmFrame.setVisible(true);
        }else if (selectedQualification.equals("MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) AND ADD MATH IN SPM C)")) {
            MatriculationAddMath matriculationaddmathFrame = new MatriculationAddMath();
            matriculationaddmathFrame.setVisible(true);
        }else if (selectedQualification.equals("MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) + MATH AND ONE OF THE SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)")) {
            MathMatric mathmatricFrame = new MathMatric();
            mathmatricFrame.setVisible(true);
        }else if (selectedQualification.equals("FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND  ADD MATH IN SPM C)")) {
            AmFoundation amfoundationFrame = new AmFoundation();
            amfoundationFrame.setVisible(true);
        }else if (selectedQualification.equals("FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND MATH + SCIENCE/TECHNOLOGY/ENGINEERING SUBJECT IN SPM C)")) {
            MFoundation mfoundationFrame = new MFoundation();
            mfoundationFrame.setVisible(true);
        }else if (selectedQualification.equals("DIPLOMA IN COMPUTING(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA COMPUTER SCIENCE(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA SOFTWARE ENGINEERING(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA INFORMATION SYSTEM(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA KEMAHIRAN MALAYSIA(DKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA VOKASIONAL MALAYSIA(DVM) ON COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)") ||
            selectedQualification.equals("DIPLOMA LANJUTAN KEMAHIRAN MALAYSIA(DLKM) IN COMPUTING FIELDS(PASS WITH A MINIMUM CGPA OF 2.50)")) {
            DiplomaCs diplomacsFrame = new DiplomaCs();
            diplomacsFrame.setVisible(true);
        }else if (selectedQualification.equals("DIPLOMA IN SCIENCE AND TECHNOLOGY(PASS WITH A MINIMUM CGPA OF 2.75)")) {
            SciDiploma scidiplomaFrame = new SciDiploma();
            scidiplomaFrame.setVisible(true);
        }else if (selectedQualification.equals("STPM(PASS WITH GRADE C(CGPA 2.00) IN ANY 2 SUBJECTS AND MATH SPM)")) {
            STPMIT itstpmFrame = new STPMIT();
            itstpmFrame.setVisible(true);
        }else if (selectedQualification.equals("MATRICULATION (PASS WITH MINIMUM (CGPA 2.00) AND MATH SPM C)")) {
            MatricIt matricitFrame = new MatricIt();
            matricitFrame.setVisible(true);
        }else if (selectedQualification.equals("FOUNDATION IN INFORMATION TECHNOLOGY(PASS WITH MINIMUM CGPA 2.00 AND MATH(SPM) C)")) {
            ItFoundation itfoundationFrame = new ItFoundation();
            itfoundationFrame.setVisible(true);
        }else if (selectedQualification.equals("FOUNDATION IN COMPUTER SCIENCE(PASS WITH MINIMUM CGPA 2.00 AND MATH(SPM) C)")) {
            ItFoundation itfoundationFrame = new ItFoundation();
            itfoundationFrame.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
    }//GEN-LAST:event_jComboBox1ActionPerformed
     private void showUserGuide() {
        String message = "Please choose one qualification from the dropdown menu and click 'Enter your grade/CGPA'.";
        JOptionPane.showMessageDialog(this, message, "User Guide", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Last.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Last().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
}
