/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashSet;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Set;
import javax.swing.JComboBox;

public class Spm extends javax.swing.JFrame {
    
    /**
     * Creates new form Spm
     */
    public Spm() {
        initComponents();
        showUserGuide2();
        setLocationRelativeTo(null);
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcombobox1 = new javax.swing.JComboBox<>();
        vMathSpm3 = new javax.swing.JComboBox<>();
        jcombobox2 = new javax.swing.JComboBox<>();
        jcombobox3 = new javax.swing.JComboBox<>();
        jcombobox4 = new javax.swing.JComboBox<>();
        jComboBox0 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        vMathSpm4 = new javax.swing.JComboBox<>();
        vMathSpm5 = new javax.swing.JComboBox<>();
        vMathSpm6 = new javax.swing.JComboBox<>();
        vMathSpm7 = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Subject");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Grade");

        jcombobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physics", "Chemistry\t", "Biology\t", "Additional Science", "Additional Mathematics\t" }));

        vMathSpm3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "C+", "C" }));
        vMathSpm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMathSpm3ActionPerformed(evt);
            }
        });

        jcombobox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chemistry\t", "Physics", "Biology\t", "Additional Science", "Additional Mathematics\t" }));

        jcombobox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economics", "Entrepreneurial Studies", "Business", "Principles of Accounting", "Geography", "Visual Arts", "Music Education", "Sports Science", "Agriculture ", "Technical Graphics Communication", "Sustainability Basic", "Design", "Mechanical Engineering Studies", "Civil Engineering Studies", "Home Science", "Computer Science", "Sports Science", "Engineering Drawing" }));

        jcombobox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrepreneurial Studies", "Business", "Principles of Accounting", "Economics", "Geography", "Visual Arts", "Music Education", "Sports Science", "Agriculture ", "Technical Graphics Communication", "Sustainability Basic", "Design", "Mechanical Engineering Studies", "Civil Engineering Studies", "Home Science", "Computer Science", "Sports Science", "Engineering Drawing" }));
        jcombobox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombobox4ActionPerformed(evt);
            }
        });

        jComboBox0.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mathematics" }));

        jButton1.setText("Recommend");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vMathSpm4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "C+", "C", " " }));
        vMathSpm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMathSpm4ActionPerformed(evt);
            }
        });

        vMathSpm5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "C+", "C" }));
        vMathSpm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMathSpm5ActionPerformed(evt);
            }
        });

        vMathSpm6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "C+", "C" }));
        vMathSpm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMathSpm6ActionPerformed(evt);
            }
        });

        vMathSpm7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "C+", "C" }));
        vMathSpm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vMathSpm7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcombobox3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(vMathSpm7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcombobox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcombobox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcombobox4, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jComboBox0, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vMathSpm3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vMathSpm4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vMathSpm5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vMathSpm6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vMathSpm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vMathSpm5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcombobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vMathSpm4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcombobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vMathSpm7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcombobox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vMathSpm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcombobox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombobox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcombobox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Get the qualification string
    String qualification = "SPM(PASS WITH 5 CREDITS)"; // Example qualification, you should get this from your JComboBox
    char grade = 0;

    List<String> recommendedPrograms = DefinedClass.recommendPrograms(qualification, grade);
    StringBuilder message = new StringBuilder();
    message.append("Recommended programs:\n");
    for (String program : recommendedPrograms) {
        message.append(program).append("\n");
    }
    JOptionPane.showMessageDialog(this, message.toString(), "Program Recommendation", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void vMathSpm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMathSpm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vMathSpm3ActionPerformed

    private void vMathSpm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMathSpm4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vMathSpm4ActionPerformed

    private void vMathSpm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMathSpm5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vMathSpm5ActionPerformed

    private void vMathSpm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMathSpm6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vMathSpm6ActionPerformed

    private void vMathSpm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vMathSpm7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vMathSpm7ActionPerformed

    private void showUserGuide2() {
        String message = "Please enter your grade or cgpa and click the button 'recommend' to see your recommended program ";
        JOptionPane.showMessageDialog(this, message, "User Guide", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void addListeners() {
    ItemListener itemListener = new ItemListener() {
        public void itemStateChanged(ItemEvent e) {
            if (e.getStateChange() == ItemEvent.SELECTED) {
                checkForDuplicateSelections();
                
            }
        }
    };

    jcombobox1.addItemListener(itemListener);
    jcombobox2.addItemListener(itemListener);
    jcombobox3.addItemListener(itemListener);
    jcombobox4.addItemListener(itemListener);
}
    private void checkForDuplicateSelections() {
    Set<String> selectedSubjects = new HashSet<>();
    JComboBox[] comboBoxes = {jcombobox1, jcombobox2, jcombobox3, jcombobox4};
    for (JComboBox comboBox : comboBoxes) {
        String selectedSubject = (String) comboBox.getSelectedItem();
        if (selectedSubject != null && !selectedSubject.equals("Select Subject")) {
            if (selectedSubjects.contains(selectedSubject)) {
                JOptionPane.showMessageDialog(this, "Please choose subjects other than " + selectedSubject, "Error", JOptionPane.ERROR_MESSAGE);
                comboBox.setSelectedItem("Select Subject");
            } else {
                selectedSubjects.add(selectedSubject);
            }
        }
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Spm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Spm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Spm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Spm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Spm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcombobox1;
    private javax.swing.JComboBox<String> jcombobox2;
    private javax.swing.JComboBox<String> jcombobox3;
    private javax.swing.JComboBox<String> jcombobox4;
    private javax.swing.JComboBox<String> vMathSpm3;
    private javax.swing.JComboBox<String> vMathSpm4;
    private javax.swing.JComboBox<String> vMathSpm5;
    private javax.swing.JComboBox<String> vMathSpm6;
    private javax.swing.JComboBox<String> vMathSpm7;
    // End of variables declaration//GEN-END:variables


}

